'use client';
import {useCallback,useEffect,useMemo,useState,useRef} from 'react';
import {Armchair,Footprints,Smartphone,Laptop,ChevronLeft,ChevronRight,Clock3,Timer,Check,RotateCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {dailyTotals,dayKey,shiftDay,periodStats,duration,ZONE,type State,type Session,type Status} from '@/lib/time';
const labels:Record<Status,string>={away:'Away',sitting:'Sitting down',phone:'Phone',working:'Working'};
const icons={away:Footprints,sitting:Armchair,phone:Smartphone,working:Laptop};
export default function Home(){
 const [state,setState]=useState<State|null>(null),[sessions,setSessions]=useState<Session[]>([]),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rate,setRate]=useState(''),[saved,setSaved]=useState(false),[month,setMonth]=useState(()=>dayKey(Date.now()).slice(0,7)),[selected,setSelected]=useState(()=>dayKey(Date.now())),[connected,setConnected]=useState(false);
 const load=useCallback(async()=>{const r=await fetch('/api/tracker',{cache:'no-store'});const d=await r.json() as {state:State;sessions:Session[];serverNow:number;error?:string};if(!r.ok)throw new Error(d.error);setState(d.state);setSessions(d.sessions);setOffset(d.serverNow-Date.now());setConnected(true);return d;},[]);
 useEffect(()=>{load().catch(e=>{setError(e.message);setConnected(false)});const p=setInterval(()=>load().catch(()=>setConnected(false)),5000);const tick=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(p);clearInterval(tick)}},[load]);
 useEffect(()=>{if(state&&rate==='')setRate(String(state.hourlyRate/100))},[state,rate]);
 const change=useCallback(async(status:Status)=>{if(!state)throw new Error('Tracker unavailable');if(state.status===status)return;setBusy(true);setError('');try{const r=await fetch('/api/tracker',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',status,revision:state.revision})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);await load();}catch(e){setError((e as Error).message);await load().catch(()=>{});throw e;}finally{setBusy(false)}},[state,load]);
 const actionRef=useRef(change);actionRef.current=change;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'set_tracker_status',description:'Set the shared tracker status now and save the timestamp.',inputSchema:{type:'object',properties:{status:{type:'string',enum:['away','sitting','phone','working']}},required:['status'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!Object.keys(labels).includes(input.status))throw new Error('Invalid status');await actionRef.current(input.status);return{status:input.status,saved:true}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 const time=now+offset,today=dayKey(time),totals=useMemo(()=>dailyTotals(sessions,state,time),[sessions,state,time]);
 const weekday=(new Date(today+'T12:00:00Z').getUTCDay()+6)%7,week=shiftDay(today,-weekday),monthStart=today.slice(0,7)+'-01',nextMonth=new Date(Date.UTC(+today.slice(0,4),+today.slice(5,7),1)).toISOString().slice(0,10);
 const periods=[{label:'Today',...periodStats(sessions,totals,today,shiftDay(today,1))},{label:'This week',...periodStats(sessions,totals,week,shiftDay(week,7))},{label:'This month',...periodStats(sessions,totals,monthStart,nextMonth)}];
 const monthDate=new Date(month+'-01T12:00:00Z'),days=new Date(Date.UTC(monthDate.getUTCFullYear(),monthDate.getUTCMonth()+1,0)).getUTCDate(),padding=(monthDate.getUTCDay()+6)%7;
 const selectedTotals=totals[selected]??{away:0,phone:0,sitting:0,working:0};
 const moveMonth=(n:number)=>{const d=new Date(monthDate);d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7))};
 const clock=(t:number)=>new Intl.DateTimeFormat('en-US',{timeZone:ZONE,hour:'numeric',minute:'2-digit',second:'2-digit'}).format(t);
 const money=(ms:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(ms/3600000*(state?.hourlyRate??2500)/100);
 return <main>
 <header><a className="brand" href="/"><span className="brand-icon"><Armchair size={24}/></span>Sit<span className="brand-light">time</span></a><div className="header-right"><span className="shared">One shared tracker</span><span className={'connection '+(connected?'':'offline')}>{connected?'Live sync':'Connecting'}</span></div></header>
 <div className="page-heading"><div><span className="eyebrow">A LITTLE AWARENESS GOES A LONG WAY</span><h1>Make time visible.</h1></div><div className="date-label">{new Intl.DateTimeFormat('en-US',{timeZone:ZONE,weekday:'long',month:'long',day:'numeric'}).format(time)}<small>Pacific time · Week starts Monday</small></div></div>
 {error&&<div className="error" role="alert">{error}<Button variant="ghost" onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}><RotateCw size={16}/> Retry</Button></div>}
 <section className={'status-panel status-'+(state?.status??'sitting')}>
 <div className="status-controls"><div className="section-label"><span className="live-dot"/> RIGHT NOW</div><h2>{state?labels[state.status]:'Loading tracker…'}</h2><p>{state?.status==='away'?'A little break from the desk.':state?.status==='phone'?'A moment on the phone.':state?.status==='working'?'In the flow, one task at a time.':'At the desk, ready for the next thing.'}</p>
 <div className="primary-buttons">{(['sitting','away'] as Status[]).map(s=>{const Icon=icons[s];const active=s==='sitting'?state?.status!=='away':state?.status==='away';return <Button key={s} className={'status-button '+(active?'selected':'')} disabled={!state||busy||state.status===s} onClick={()=>change(s).catch(()=>{})}><Icon size={20}/>{labels[s]}{state?.status===s&&<Check size={16}/>}</Button>})}</div>
 <div className="activity-row"><span>While sitting</span>{(['phone','working'] as Status[]).map(s=>{const Icon=icons[s];return <Button key={s} variant="ghost" className={state?.status===s?'activity-active':''} disabled={!state||busy||state.status==='away'||state.status===s} onClick={()=>change(s).catch(()=>{})}><Icon size={17}/>{labels[s]}</Button>})}</div></div>
 <div className="character-scene"><div className="scene-orbit"/><div role="img" aria-label={'Cute person '+(state?labels[state.status].toLowerCase():'sitting')} className={'character '+(state?.status??'sitting')}/><span className="scene-caption">{state?.status==='away'?'BRB, taking a stroll':state?.status==='phone'?'Just one more scroll…':state?.status==='working'?'Little steps. Good work.':'Hello, little desk buddy.'}</span></div>
 <div className="session-clock"><Clock3 size={19}/><span>Current {state?.status==='away'?'away':state?.status==='phone'?'phone':'status'} session</span><strong>{state?duration(time-state.startedAt,true):'--:--:--'}</strong><small>{state?'Since '+clock(state.startedAt):'Waiting for shared status'}</small></div>
 </section>
 <section className="overview"><div className="section-title"><h2>Away at a glance</h2><span>Active time included in totals</span></div><div className="stat-grid">{periods.map(p=><article className="stat-card" key={p.label}><div className="stat-top"><h3>{p.label}</h3><Timer size={18}/></div><strong>{duration(p.total)}</strong><span className="stat-sub">Total away time</span><div className="stat-footer"><div><span>Avg. away session</span><b>{duration(p.average)}</b></div><div><span>Away cost</span><b>{money(p.total)}</b></div></div></article>)}</div><p className="average-note">Averages use completed away sessions that ended in the period. {periods[0].count} completed today.</p></section>
 <div className="lower-grid"><section className="calendar-card"><div className="section-title"><h2>Your time, day by day</h2><span>Away time</span></div><div className="calendar-heading"><Button variant="ghost" size="icon" aria-label="Previous month" onClick={()=>moveMonth(-1)}><ChevronLeft size={18}/></Button><h3>{new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(monthDate)}</h3><Button variant="ghost" size="icon" aria-label="Next month" onClick={()=>moveMonth(1)}><ChevronRight size={18}/></Button></div><div className="calendar-grid">{['M','T','W','T','F','S','S'].map((d,i)=><span className="weekday" key={i}>{d}</span>)}{Array.from({length:padding},(_,i)=><span key={'pad'+i}/>)}{Array.from({length:days},(_,i)=>{const key=month+'-'+String(i+1).padStart(2,'0');const total=totals[key]?.away??0;return <button key={key} className={'calendar-day '+(key===selected?'day-selected ':'')+(key===today?'day-today ':'')+(total?'has-time':'')} onClick={()=>setSelected(key)} aria-label={`${key}, ${duration(total)} away`} aria-pressed={key===selected}><span>{i+1}</span><small>{total?duration(total):'—'}</small></button>})}</div><div className="calendar-detail"><div><b>{new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(selected+'T12:00:00Z'))}</b><span>{selected===today?'Today':'Selected day'}</span></div>{(['away','phone','working'] as Status[]).map(s=><div key={s}><span>{labels[s]}</span><b>{duration(selectedTotals[s])}</b></div>)}</div></section>
 <div className="side-stack"><section className="rate-card"><div className="section-label">THE VALUE OF TIME</div><h2>Every minute counts.</h2><p>Set one hourly rate for everyone. Away cost uses this rate across all dates.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/tracker',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'rate',rate:rate.trim()===''?null:Number(rate)})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);await load();setSaved(true);setTimeout(()=>setSaved(false),2500);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label htmlFor="rate">Global hourly rate</label><div className="rate-input"><span>$</span><Input id="rate" type="number" min="0" max="100000" step="0.01" required value={rate} onChange={e=>setRate(e.target.value)}/><span>/ hour</span></div><Button className="save-button" type="submit" disabled={busy||!state}>{saved?<><Check size={17}/> Saved</>:'Save rate'}</Button></form></section>
 <section className="today-card"><h3>Also tracked today</h3><div><span><Smartphone size={17}/> Phone</span><b>{duration(totals[today]?.phone??0)}</b></div><div><span><Laptop size={17}/> Working</span><b>{duration(totals[today]?.working??0)}</b></div></section></div></div>
 <section className="history"><div className="section-title"><h2>Recent sessions</h2><span>Automatically saved</span></div>{!sessions.length?<p className="empty">Your first completed session will appear here. Choose a status above to get started.</p>:<div className="history-list">{sessions.slice(0,8).map(s=>{const Icon=icons[s.status];return <div key={s.id}><span className={'history-icon '+s.status}><Icon size={18}/></span><b>{labels[s.status]}</b><span>{dayKey(s.start)} · {clock(s.start)} – {clock(s.end)}</span><strong>{duration(s.end-s.start)}</strong></div>})}</div>}</section>
 <footer><span>Sit time <span>·</span> Small moments, clearly counted.</span><span>Shared status refreshes every 5 seconds.</span></footer>
 </main>
}
