export const ZONE='America/Los_Angeles';
export type Status='away'|'sitting'|'phone'|'working';
export type Session={id:string;status:Status;start:number;end:number};
export type State={status:Status;startedAt:number;revision:number;hourlyRate:number};
export function dayKey(t:number) { const p=new Intl.DateTimeFormat('en-CA',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(t);return ['year','month','day'].map(k=>p.find(x=>x.type===k)!.value).join('-'); }
export function shiftDay(day:string,n:number){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export function midnight(day:string){const target=Date.parse(day+'T00:00:00Z');let t=target;for(let i=0;i<3;i++){const p=new Intl.DateTimeFormat('en-US',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(t);const v=(k:string)=>p.find(x=>x.type===k)!.value;const actual=Date.parse(`${v('year')}-${v('month')}-${v('day')}T${v('hour')}:${v('minute')}:${v('second')}Z`);t+=target-actual;}return t;}
export function dailyTotals(sessions:Session[],state:State|null,now:number){const result:Record<string,Record<Status,number>>={};const all=state?[...sessions,{id:'active',status:state.status,start:state.startedAt,end:Math.max(now,state.startedAt)}]:sessions;for(const s of all){if(s.status!=='away'&&s.status!=='phone')continue;let cursor=s.start;while(cursor<s.end){const key=dayKey(cursor);const end=Math.min(s.end,midnight(shiftDay(key,1)));if(end<=cursor)break;result[key]??={away:0,sitting:0,phone:0,working:0};result[key][s.status]+=end-cursor;cursor=end;}}return result;}
export function periodStats(sessions:Session[],totals:ReturnType<typeof dailyTotals>,start:string,end:string,kind:'away'|'phone'='away'){let total=0;for(const [day,v] of Object.entries(totals))if(day>=start&&day<end)total+=v[kind];const completed=sessions.filter(s=>s.status===kind&&dayKey(s.end)>=start&&dayKey(s.end)<end);return {total,average:completed.length?completed.reduce((sum,s)=>sum+s.end-s.start,0)/completed.length:0,count:completed.length};}
export function duration(ms:number,seconds=false){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60);return seconds?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`:h?`${h}h ${m}m`:m?`${m}m ${s%60}s`:`${s}s`;}
